/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_iki_nop_neuromancer_ResonanzEngine */

#ifndef _Included_fi_iki_nop_neuromancer_ResonanzEngine
#define _Included_fi_iki_nop_neuromancer_ResonanzEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    startRandomStimulation
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_startRandomStimulation
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    startMeasureStimulation
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_startMeasureStimulation
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    startOptimizeModel
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_startOptimizeModel
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    startExecuteProgram
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[[FZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_startExecuteProgram
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobjectArray, jobjectArray, jboolean, jboolean);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    startMeasureProgram
 * Signature: (Ljava/lang/String;[Ljava/lang/String;I)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_startMeasureProgram
  (JNIEnv *, jobject, jstring, jobjectArray, jint);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    stopCommand
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_stopCommand
  (JNIEnv *, jobject);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    isBusy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_isBusy
  (JNIEnv *, jobject);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    getStatusLine
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_getStatusLine
  (JNIEnv *, jobject);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    getAnalyzeModel
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_getAnalyzeModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    getDeltaStatistics
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_getDeltaStatistics
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    getLastExecutedProgramStatisics
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_getLastExecutedProgramStatisics
  (JNIEnv *, jobject);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    deleteModelData
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_deleteModelData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    setEEGSourceDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_setEEGSourceDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    getEEGSourceDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_getEEGSourceDevice
  (JNIEnv *, jobject);

/*
 * Class:     fi_iki_nop_neuromancer_ResonanzEngine
 * Method:    getEEGDeviceStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fi_iki_nop_neuromancer_ResonanzEngine_getEEGDeviceStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
